// Magyar szólista a páros játékhoz
// Betűnként rendezett, érvényes szavak
const VALID_WORDS = new Set([
  // A
  "ALMA","AUTÓ","ABLAK","ASZTAL","ÁGYÚ","ÁLLAT","ANYA","APA","ARANY","ALAP",
  "ARCÉL","AKCIÓ","AJAK","ALAP","ANGYAL","ÁPRILIS","ASZFALT","AJTÓ","ÁRAM","ARÁNY",
  "AVATÁR","ÁLTALÁNOS","ALFÖLD","ÁBRÁZAT","ALAGÚT","ANGLIA","ARAB","ALKAR","AKOL","ADÓ",
  // Á
  "ÁLLOMÁS","ÁRUHÁZ","ÁFONYA","ÁGNES","ÁLOM","ÁSVÁNYI","ÁRBOC","ÁTJÁRÓ","ÁRTÉR","ÁTLAG",
  // B
  "BÉKA","BÁRÁNY","BOGÁR","BÚTOR","BŐRÖND","BARACK","BANÁN","BIRKA","BIKA","BÁLNA",
  "BABÉR","BAGOLY","BAJNOK","BAKONY","BALKON","BARLANG","BÁSTYA","BETEG","BICIKLI","BIRODALOM",
  "BOLT","BORDA","BORSÓ","BÚZA","BURGONYA","BUZOGÁNY","BARÁT","BÁLINT","BOGÁNCS","BÉGETŐ",
  // C
  "CIPŐ","CSIRKE","CITROM","CUKOR","CSIZMA","CSILLAG","CSÓNAK","CSEPPKŐ","CERUZA","CÁPA",
  "CSOKOL","CSAPAT","CÉLPONT","CÉDRUS","CSŐRÖS","CSENGŐ","CSERKÉSZ","CSIGAHÁZ","CSIPKE","CSODÁS",
  // D
  "DIÓFA","DELFIN","DINNYE","DISZNÓ","DOBOZ","DOMBORÚ","DRÁGA","DUDÁS","DÜBÖRGÉS","DÓZSA",
  "DARAB","DÁRDA","DENEVÉR","DEREK","DERVIS","DESZKA","DICSŐ","DIÁK","DINASZTIA","DIÓ",
  // E
  "EGÉR","ELEFÁNT","ERDŐ","ERŐ","ÉTEL","EZÜST","EJTŐERNYŐ","EPER","ESTE","EMBER",
  "ÉGBOLT","ÉNEKES","ÉDESSÉG","ÉLELEM","ÉREM","ÉRCBÁNYA","ÉLŐLÉNY","ÉRINTŐ","ÉRTELEM","EREKLYE",
  // F
  "FOCILABDA","FOLYÓ","FARKAS","FELHŐ","FESTÉK","FÜGE","FORGÓ","FÁK","FÉSZEK","FAKÍR",
  "FALEVÉL","FELESÉG","FÉLELEM","FÉNY","FENYŐ","FIATAL","FIÓK","FOGOLY","FOLT","FORRÁS",
  "FŐVÁROS","FÚRÓGÉP","FUVOLA","FÜRDŐ","FÜST","FUTÁR","FUTBALL","FÜZET","FŰSZER","FŰTÉS",
  // G
  "GALAMB","GOMBA","GÖRÖG","GYÜMÖLCS","GYÖKÉR","GAZELLA","GITÁR","GÓLYA","GÓBÉ","GYÉMÁNT",
  "GALOP","GARAT","GAZDAGSAG","GERELY","GERINCE","GESZTENYÉS","GŐZÖS","GÖRBE","GRÚZ","GUBÓ",
  "GYAPJÚ","GYEREK","GYERTYA","GYILKOS","GYÖNGY","GYŐZTES","GYÚJTÓ","GYŰRŰ","GÉPÉSZ","GÉSA",
  // H
  "HÁZ","HOLD","HAJÓ","HEGEDŰ","HEGY","HETES","HORGÁSZ","HÚSVÉT","HÍD","HOMOK",
  "HABOS","HAJTŰ","HALÁSZ","HALCYON","HARANG","HARCOS","HASZON","HATALOM","HATÁR","HÁLÓS",
  "HÉJA","HINTA","HOROG","HORPASZ","HOSSZÚ","HŐMÉRŐ","HULLÁM","HÚROS","HŰTŐ","HŰVÖS",
  // I
  "ISZAP","ISKOLA","IBOLYA","IKER","IRÁNY","IPAR","INDIÁN","INDÍTÉK","INGA","INTÉZET",
  "IRAT","ISTEN","ITTHON","IVADÉK","IZOM","ÍZÜLETI","IRÓ","ÍRÓGÉP","ISMERŐS","IGAZSÁG",
  // Í
  "ÍVELT","ÍJÁSZ","ÍNYENC","ÍRÁS","ÍRISZ",
  // J
  "JÁTÉK","JÉGKRÉM","JUHAR","JUHÁSZ","JÁRDA","JÁRVÁNY","JÓSÁG","JÓSLAT","JÖVEDELEM","JÓTÉKONY",
  "JABIRU","JAGUÁR","JANCSIKA","JAPÁN","JÁRTASSÁG","JEGES","JELKÉP","JELSZÓ","JELENET","JELLEG",
  // K
  "KUTYA","KALAND","KANÁL","KAPOR","KARCOS","KASTÉLY","KECSKE","KENGYEL","KÉREGFA","KERT",
  "KESZTYŰ","KÉZ","KIRÁNDULÁS","KISLÁNY","KISFILM","KISKAPU","KISZOLGÁL","KITÖRÉS","KLUB","KOBOLD",
  "KOCKA","KÓKUSZ","KÓRUS","KOVÁCS","KŐBÁNYA","KÖNNYŰ","KŐRIS","KÖTET","KÖVETŐ","KÖZÉP",
  "KULCS","KUKORICA","KUNYHÓ","KUPOLA","KÚT","KÜZDELEM","KÜRTŐ","KVÁZI","KÉRDÉS","KÍSÉRTET",
  // L
  "LABDA","LÁMPA","LAPÁT","LAZAC","LEÁNY","LÉGGÖMB","LÉGVÁR","LEPKE","LILIOM","LISZT",
  "LOVAS","LUGAS","LÚDTOLL","LÁNDZSA","LÁTVÁNY","LÉGZÉS","LELTÁR","LENDÜLET","LEVEGŐ","LEKVÁR",
  // M
  "MACSKA","MADÁR","MAJOM","MÁLNA","MANGÓ","MARHA","MEDVE","MÉHKAS","MÉLTÓ","MESEKÖNYV",
  "METRÓ","MÉZESKALÁCS","MIKROFON","MOCSÁR","MOGYORÓ","MOSOLY","MOTOROS","MÓKUS","MÚZEUM","MŰHELY",
  "MÁGUS","MÁLHA","MÁLYVA","MÁMOR","MÁRVÁNY","MÁSVILÁG","MÁRCIUS","MÁRTON","MÁSIK","MÁTKA",
  // N
  "NARANCS","NAPFÉNY","NEKTÁR","NEFELEJCS","NEMES","NÉPDAL","NÉZŐPONT","NYARALÁS","NYÁR","NYÚL",
  "NÁDAS","NÁDSZÁL","NÁBOB","NAPSUGÁR","NAPLÓ","NAPTÁR","NAPLEMENTE","NARANCSSÁRGA","NEDVES","NEMESSÉG",
  "NŐVÉR","NYAK","NYÍRFA","NYILVÁNOS","NYÍL","NYILATKOZAT","NYILVÁNVALÓ","NYOMDA","NYOMOZÓ","NYÚJTÓ",
  // O
  "ORGONA","OROSZLÁN","OSZTÁLY","OLTÁR","OLVADÁS","OPÁL","ORCA","OTTHON","OVÁLIS","OLDAL",
  "OLDALAS","OLTÓANYAG","OLIMPIA","OMLADÉK","OMLETT","ONYX","OPERA","ORVOS","ÖREG","ÖSSZEG",
  // Ó
  "ÓCEÁN","ÓKOR","ÓRIÁS","ÓLOM","ÓVODA","ÓVATOS",
  // Ö
  "ÖBÖL","ÖLTÖZŐ","ÖRVÉNY","ÖSSZHANG","ÖSZTÖN","ÖTLET","ÖVEZET","ÖRVÖS","ŐSZ","ÖREG",
  // Ő
  "ŐRSZEM","ŐSLÉNY","ŐSTÖRTÉNET","ŐRZÉS",
  // P
  "PÁLMA","PANDA","PAPAGÁJ","PARADICSOM","PÁRDUC","PÁVA","PÉKSÉG","PILLANGÓ","PINTÉR","POHÁR",
  "POLÁR","PORTA","POSTÁS","PÓLÓ","PRÉS","PRÓBA","PAJZS","PAKSAMÉTA","PALACK","PALÁNK",
  "PALACSINTA","PALOTA","PÁLINKA","PÁLYÁZAT","PÁNCÉL","PÁRIZS","PÁRKÁNY","PÁRTA","PÁSZTOR","PATIKA",
  // R
  "RÓZSA","RADÍR","RAKÉTA","RAVASZ","REGGEL","REMÉNY","REND","REPÜLŐ","RÉPA","RETEK",
  "RÉTES","RIADÓ","RIGÓ","RÍTUS","ROBOT","ROMOK","RÓZSAKERT","RÖPLABDA","RUGÓ","RÜGY",
  // S
  "SÁRKÁNY","SÁRGA","SÁRMÁNY","SÁTOR","SÁFRÁNY","SAROK","SARLÓ","SAVÓ","SAJT","SÍELŐ",
  "SÍKSÁG","SÓLYOM","SÓVÁRGÁS","SÓVIDÉK","SÖRÉNY","STUCC","SÜLDŐ","SÜTŐ","SZARVAS","SZARVASBŐR",
  // SZ
  "SZABAD","SZABÓ","SZAKÁCS","SZÁLLODA","SZAMÁR","SZAMÉBA","SZARV","SZÉLCSEND","SZÉLKAKAS","SZÉLMALOM",
  "SZERELEM","SZEREPLŐ","SZIGET","SZIKRA","SZILFA","SZILVA","SZÍN","SZITA","SZOBA","SZOBOR",
  "SZOMJAS","SZONETT","SZŐKE","SZŐLŐ","SZÖVEG","SZÚNYOG","SZÜRKE","SZÜRET","SZÜRKÜLET","SZÜLETÉS",
  // T
  "TÁBOR","TÁJKÉP","TALICSKA","TANÁR","TÁNCOS","TAVASZI","TAVASZ","TEHER","TEJFÖL","TENISZ",
  "TENGER","TÉRKÉP","TÜCSÖK","TÜNDÉR","TÜSKE","TŰZHÁNYÓ","TIGRIS","TITOK","TOJÁS","TORONY",
  "TÖLGY","TÖMEG","TÖRVÉNY","TRÓFEA","TUDOMÁNY","TULIPÁN","TÜNDÖKLÉS","TÜRELEM","TŰZKŐ","TÁBLA",
  // U
  "UTAZÁS","UBORKA","UJJLENYOMAT","UNOKA","URÁLI","URÁN","UTCA","ÚTJELZŐ","UTÓD","ÜVEG",
  // Ú
  "ÚSZÁS","ÚTVONAL","ÚTTEST","ÚJONC",
  // Ü
  "ÜNNEP","ÜGYVÉD","ÜLŐKE","ÜVÖLTÉS","ÜZENET","ÜZLET",
  // Ű
  "ŰRHAJÓ","ŰRLÉNY","ŰRUTAZÁS",
  // V
  "VADÁSZ","VAKOND","VÁLYOG","VÁNDOR","VARÁZSLÓ","VARJÚ","VÁSZON","VÉDELEM","VENDÉG","VETÉS",
  "VEZÉR","VIDÉK","VILÁG","VIRÁG","VITÉZ","VÍZESÉS","VÍZILABDA","VÖLGY","VÖRÖS","VÖDÖR",
  // Z
  "ZSIRÁF","ZÚZMARA","ZÖRGŐS","ZÖLDES","ZÖLDSÉG","ZONGORA","ZUHANY","ZUHATAG","ZEBRA","ZUZMÓ",
  // ZS
  "ZSIVÁNY","ZSOKÉ","ZSÚFOLT","ZSÁLYA","ZSÁKMÁNY","ZSEBKENDŐ",
]);

function isValidWord(word) {
  return VALID_WORDS.has(word.toUpperCase().trim());
}
